"""initial migration

Revision ID: 1e5225defc50
Revises: 
Create Date: 2025-09-13 15:48:39.073570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5225defc50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_gambar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gambar', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_glcm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('energi', sa.Float(), nullable=False),
    sa.Column('homogenitas', sa.Float(), nullable=False),
    sa.Column('kontras', sa.Float(), nullable=False),
    sa.Column('korelasi', sa.Float(), nullable=False),
    sa.Column('dismilaritas', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_hsv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hue_mean', sa.Float(), nullable=False),
    sa.Column('hue_std', sa.Float(), nullable=False),
    sa.Column('sat_mean', sa.Float(), nullable=False),
    sa.Column('sat_std', sa.Float(), nullable=False),
    sa.Column('val_mean', sa.Float(), nullable=False),
    sa.Column('val_std', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('plain_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tb_dataset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gambar', sa.Integer(), nullable=True),
    sa.Column('kelas', sa.String(length=25), nullable=False),
    sa.Column('nilai_hsv', sa.Integer(), nullable=True),
    sa.Column('nilai_glcm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gambar'], ['tb_gambar.id'], ),
    sa.ForeignKeyConstraint(['nilai_glcm'], ['tb_glcm.id'], ),
    sa.ForeignKeyConstraint(['nilai_hsv'], ['tb_hsv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_klasifikasi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gambar', sa.Integer(), nullable=True),
    sa.Column('jarak', sa.Float(), nullable=True),
    sa.Column('kelas', sa.String(length=25), nullable=False),
    sa.Column('nilai_hsv', sa.Integer(), nullable=True),
    sa.Column('nilai_glcm', sa.Integer(), nullable=True),
    sa.Column('nilai_akurasi', sa.Float(), nullable=True),
    sa.Column('tanggal_klasifikasi', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['gambar'], ['tb_gambar.id'], ),
    sa.ForeignKeyConstraint(['nilai_glcm'], ['tb_glcm.id'], ),
    sa.ForeignKeyConstraint(['nilai_hsv'], ['tb_hsv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_klasifikasi')
    op.drop_table('tb_dataset')
    op.drop_table('tb_user')
    op.drop_table('tb_hsv')
    op.drop_table('tb_glcm')
    op.drop_table('tb_gambar')
    # ### end Alembic commands ###
